name: Manage Gists

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'read'
        type: choice
        options:
          - read
          - modify
          - add
      hash:
        description: 'Hash value'
        required: true
        default: ''
      ip:
        description: 'IP address'
        required: false
        default: ''

jobs:
  gist_management:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Gist Management Script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python .github/workflows/manage_gist.py "${{ github.event.inputs.action }}" "${{ github.event.inputs.hash }}" "${{ github.event.inputs.ip }}"
